### ISSUE TITLE
invalid config for ga: yaml: did not find expected key

### ISSUE THREAD

**Issue by matthysdebruyn-wdfc** [bithauschile/datadog-ga#9]
**Datadog agent version**: 6.5.0

> c:\Program Files\Datadog\Datadog Agent\embedded>agent.exe check ga
> 
> Error: invalid config for ga: yaml: line 12: did not find expected key
> Error: no valid check found

OS: Windows Server 2016
Key location: c:\programdata\datadog\conf.d\ga.d\key.json

Below is file extract:

```
init_config:
    min_collection_interval: 55
    service_account_email: datadog@test-datadog-integration.iam.gserviceaccount.com
    key_file_location: c:\programdata\datadog\conf.d\ga.d\key.json
   
   - profile: ga:122299569
     tags:
      - env:prd
     pageview_dimensions:
      - rt:country
      - rt:city
      - rt:deviceCategory
```
